### ISSUE TITLE
Multi Window iPad Popups opening on ALL windows

### ISSUE THREAD

**Issue by epickid976** [Mijick/Popups#124]
On iPad, when using multiwindow and opening a popup, it opens on all open windows. Regardless of whether the window opening the popup is displayed on all windows or not.

**Comment by FulcrumOne** [comment]
Hey @epickid976,

The problem above is in our [backlog](https://mijick.notion.site/c95fe641ff684561a4523b9570113516?v=ef1470d24ddb43beab098384f6ae6676) for the current sprint, which we start this Wednesday.

As for the technical explanation of why this bug happens - it's because we implemented this library with singletons; there's only one popup stack, regardless of the number of windows (which is a problem on both Mac and iPad). 

Nevertheless the problem will be solved this or next week 😉

Thanks for your ticket and have a nice day,
Tomasz

**Comment by epickid976** [comment]
I just updated to the new 3.0 patch but I still have this issue. Any ideas?

**Comment by FulcrumOne** [comment]
Hey @epickid976,

It works:
https://github.com/user-attachments/assets/3236da74-ded7-4fe4-a943-f49104534770
However, most likely it is my fault because I wrote documentation that nobody but me understands 😅

Could I ask you to read this and tell me whether it's clear for you or I should rewrite this section? Thanks for your help! 
![CleanShot 2024-10-21 at 17 15 21](https://github.com/user-attachments/assets/b21262f0-2aa4-4ad5-849b-312885961d3c)
![CleanShot 2024-10-21 at 17 15 35](https://github.com/user-attachments/assets/3ab6e217-1116-4c5a-bc94-70817e2b17bb)

**Comment by FulcrumOne** [comment]
Ohhh, I see. It's a use case I hadn't considered, and I'm not sure if anything can be done about it (the framework creates a stack of popups for each window). I'll think of some workaround over the weekend though and return to you ASAP. 

Have a nice day,
Tomasz

**Comment by epickid976** [comment]
Thanks I'd really appreciate it because I was breaking my head trying to figure it out 😂
