### ISSUE TITLE
How to implement the hideOverlay() function like 2.7.0. I didn't find the relevant API in 3.0.0

### ISSUE THREAD

**Issue by mytianer** [Mijick/Popups#150]
In previous versions, after using hideOverlay(), the view under the popup can still be interacted

**Comment by FulcrumOne** [comment]
Hey @mytianer,

This option was moved directly into the popup. Use it in the `configurePopup` method:

![CleanShot 2024-10-25 at 10 48 24](https://github.com/user-attachments/assets/62ed9d29-b188-4b34-867a-bf8dbefc1577)

![CleanShot 2024-10-25 at 10 48 31](https://github.com/user-attachments/assets/1f90de7a-ae2c-4375-8bcf-51fe1c7b3613)

**Comment by mytianer** [comment]
I have used .overlayColor(.clear) in the new version. But the problem is that the view under the popup cannot be interacted with
![Uploading 截屏2024-10-25 17.05.11.png…]()

**Comment by mytianer** [comment]
I have used .overlayColor(.clear) in the new version. But the problem is that the view under the popup cannot be interacted with
<img width="656" alt="截屏2024-10-25 17 05 11" src="https://github.com/user-attachments/assets/3c71bbfe-1729-4e45-91b7-f7ab5d587852">

**Comment by FulcrumOne** [comment]
Oh, I see. Seems that when designing this functionality, my goal was to catch "tap outside" event rather than interaction with the content. I'll have to rethink this issue, but unfortunately I don't have time to deal with it right now because I'm working on the framework's readme file, which I have to finish by Tuesday.

![CleanShot 2024-10-25 at 11 12 31](https://github.com/user-attachments/assets/3e449571-4e5b-4203-a5ff-5ea659765ce8)

However you can fix it very easily - just replace `.black.opacity(0.0000000001)` with `.clear` and it will work as you want. I'm super sorry for this, but I had completely missed this use case.

Have a nice day,
Tomasz

**Comment by mytianer** [comment]
Thank you very much for reply, now it works well

**Comment by FulcrumOne** [comment]
Hey @mytianer,

Just letting you know that this feature returned in the version 4.0.0.

Have a nice day,
Tomasz
